steps:
    - name: 'gcr.io/cloud-builder/gcloud'
      entrypoint: 'bash'
      args: ['echo', 'prepare to build image...']

    - name: 'gcr.io/cloud-builder/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/voice_analysis_image:latest', '.']
        
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/voice_analysis:latest']

    - name: 'gcr.io/cloud-builders/docker'
      args: ['run', '-it', '-p', '8080:5000', 'gcr.io/$PROJECT_ID/voice_analysis_image:latest', '/bin/bash']

    - name: 'bash'
      args: ['mlchain', 'run']

      