name: mlchain-voice-server # name of service
entry_file: server.py # python file contains object ServeModel
host: localhost # host service
port: 5000 # port service
server: flask # option flask or quart or grpc
wrapper: gunicorn # option None or gunicorn or hypercorn
cors: true
dump_request: None # None or path folder log request
version: '1.0.0'
gunicorn: # config apm-server if uses gunicorn wrapper
  timeout: 60
  keepalive: 60
  max_requests: 0
  threads: 1
  worker_class: 'gthread'
  umask: '0'
mode:
  default: dev  # running mode
  env:   # set of mode env
    default: {}   # environ default
    dev: {} # environ by mode
    prod: {} # environ by mode
